[package]
name = "sc-liquid-staking-mock-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.sc-liquid-staking-mock]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.36.1"
