////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    sc_liquid_staking_mock
    (
        callBack
        claim
        clearRewardsAmounts
        clearRewardsFinished
        clearRewardsStarted
        clearValidatorStakeAmounts
        clearValidators
        dailyDelegation
        delegateAdmin
        delegate_direct
        distributeProtocolRevenue
        getDeltaStake
        getExchangeRate
        getExchangeRateMultiplier
        getExchangeRateUpdateFinished
        getFlag
        getMappingIndex
        getMinValue
        getProtocolRevenue
        getRedelegateFinished
        getRedelegateMappingIndex
        getRedelegateStarted
        getRewardsAdmin
        getRewardsAmount
        getRewardsAmounts
        getRewardsInfoFinished
        getRewardsInfoStarted
        getRewardsMappingIndex
        getServiceFee
        getStEgldId
        getStakeAdmin
        getStakeAmounts
        getStakeInfoFinished
        getStakeInfoStarted
        getStakeValue
        getTotalStaked
        getTotalTokenSupply
        getUEgldId
        getValidatorStakeAmount
        getValidators
        getValidatorsCount
        getWithdrawFinished
        getWithdrawMappingIndex
        getWithdrawStarted
        issueToken
        issueUndelegatedToken
        push_validators
        redelegateAdmin
        setDeltaStake
        setLocalRoles
        setMappingIndex
        setRewardsMappingIndex
        setServiceFee
        setTotalStaked
        setValidatorStakeAmount
        stake
        undelegate_direct
        unstake
        updateExchangeRate
        withdrawAdmin
    )
}
