////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    sc_liquid_staking_mock
    (
        callBack
        claim
        clearRewardsAmounts
        clearValidators
        daily_delegation
        delegateAdmin
        delegate_direct
        delegate_test
        distributeProtocolRevenue
        getCallbackResult
        getDeltaStake
        getEpochValidators
        getExchangeRate
        getFilteredStakeAmounts
        getFilteredStakeAmountsLength
        getMappingIndex
        getProtocolRevenue
        getRewardsAdmin
        getRewardsAmount
        getRewardsAmounts
        getRewardsInfoFinished
        getRewardsMappingIndex
        getServiceFee
        getStEgldId
        getStakeAdmin
        getStakeAmounts
        getStakeInfoFinished
        getTotalStaked
        getTotalTokenSupply
        getUEgldId
        getUsedValidators
        getValidatorStakeAmount
        getValidators
        getValidatorsCount
        issueToken
        issueUndelegatedToken
        push_validators
        redelegate
        setDeltaStake
        setLocalRoles
        setMappingIndex
        setRewardsMappingIndex
        setServiceFee
        setTotalStaked
        stake
        undelegate_direct
        unstake
        updateExchangeRate
    )
}
