////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    sc_liquid_staking_mock
    (
        callBack
        claim
        clearRewardsAmounts
        clearValidatorStakeAmounts
        clearValidators
        dailyDelegation
        delegateAdmin
        delegate_direct
        delegate_test
        distributeProtocolRevenue
        getCallbackResult
        getDeltaStake
        getEpochValidators
        getExchangeRate
        getFilteredStakeAmounts
        getFilteredStakeAmountsLength
        getFlag
        getMappingIndex
        getMinValue
        getProtocolRevenue
        getRewardsAdmin
        getRewardsAmount
        getRewardsAmounts
        getRewardsInfoFinished
        getRewardsMappingIndex
        getServiceFee
        getStEgldId
        getStakeAdmin
        getStakeAmounts
        getStakeInfoFinished
        getTotalStaked
        getTotalTokenSupply
        getUEgldId
        getUsedValidators
        getValidatorStakeAmount
        getValidators
        getValidatorsCount
        getWithdrawFinished
        getWithdrawMappingIndex
        issueToken
        issueUndelegatedToken
        push_validators
        redelegate
        setDeltaStake
        setLocalRoles
        setMappingIndex
        setRewardsMappingIndex
        setServiceFee
        setTotalStaked
        setValidatorStakeAmount
        stake
        undelegate_direct
        unstake
        updateExchangeRate
        withdrawTask
    )
}
